//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicChange.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseExternalPlayer {
            get {
                return ((bool)(this["UseExternalPlayer"]));
            }
            set {
                this["UseExternalPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vlc")]
        public string PreferredPlayer {
            get {
                return ((string)(this["PreferredPlayer"]));
            }
            set {
                this["PreferredPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoFullscreen {
            get {
                return ((bool)(this["AutoFullscreen"]));
            }
            set {
                this["AutoFullscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MinimizeOnExternalLaunch {
            get {
                return ((bool)(this["MinimizeOnExternalLaunch"]));
            }
            set {
                this["MinimizeOnExternalLaunch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomPlayerPath {
            get {
                return ((string)(this["CustomPlayerPath"]));
            }
            set {
                this["CustomPlayerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public string VideoVolume {
            get {
                return ((string)(this["VideoVolume"]));
            }
            set {
                this["VideoVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastVideoPath {
            get {
                return ((string)(this["LastVideoPath"]));
            }
            set {
                this["LastVideoPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MaximizeVideoOnLoad {
            get {
                return ((bool)(this["MaximizeVideoOnLoad"]));
            }
            set {
                this["MaximizeVideoOnLoad"] = value;
            }
        }

		public float VideoBrightness
		{
			get;
			internal set;
		}
		public float VideoContrast
		{
			get;
			internal set;
		}
		public float VideoSaturation
		{
			get;
			internal set;
		}
		public float VideoGamma
		{
			get;
			internal set;
		}
	}
}
